### ISSUE TITLE
Not possible to persistently change downloads dir from the default inside jail

### ISSUE THREAD

**Issue by urza** [freenas/iocage-plugin-transmission#3]
Hi, I just installed transmission plugin in FreeNAS-11.2-U3 

All settings work fine except changing the download-dir. It is reverted to default value "/usr/local/etc/transmission/home/Downloads" every time the plugin is restarted.
All other settings are preserved correctly across restarts.

Changing settings.json in /transmission/home did not help, I needed to change  last line in "...iocage/jails/transmission/root/etc/rc.conf" where "transmission_download_dir=xxx" is hardcoded to the default value. After changing this line to my desired mounted dir, it works as expected.

**Comment by itskando** [comment]
+1.

Possible fix [here](https://www.ixsystems.com/community/threads/cannot-set-custom-download-folder-for-transmission-and-two-udp-errors-when-starting-transmission.70706/).

**Comment by josh4trunks** [comment]
The post-install.sh script shouldn't be setting "transmission_download_dir" since that will cause this to be hard set in transmission. The temporary fix for users is to run ```sysrc 'transmission_download_dir='```.

For this plugin, we should also set "transmission_download_dir" to a blank value during post-install.sh
This is exactly how I handled it in the old PBI version of the plugin, see here https://github.com/josh4trunks/freenas-plugins/blob/master/plugins/transmission/scripts/post-install.sh.

**Comment by MiwiDots** [comment]
Is fixed now, thanks

**Comment by josh4trunks** [comment]
:+1:
